#+TITLE: SICP: Exercises's Solutions
#+DESCRIPTION: Answers for the exercises on the book Structure and Interpretation of Computer Programs, written by Harold Abelson, Gerald Jay Sussman and Julie Sussman.
#+AUTHOR: Lucas Vieira
#+EMAIL: lucasvieira@lisp.com.br
#+LANGUAGE: en-us
#+OPTIONS: toc:nil

* Index

- [[./ch-01.org][Chapter 1]]
- [[./ch-02.org][Chapter 2]]
- Chapter 3
- Chapter 4
- Chapter 5

Currently at Chapter 2.

* What?

I wanted to keep track of the exercises I've been answering. Notice that the answers here contained are not necessarily the best approach, and also
may not be correct. So don't be a douche and think that you can straight up copy or cheat by not answering the book's exercises because, if you can't do it
without cheating, you're not learning anything at all.

All exercises involving actual programming were tested under Chez Scheme.

* Why?

Again, I wanted to keep track of it. And since these answers are not really a secret, I figured I'd just throw them in a repo.
Also, while I'm at it, I'm trying to use org-mode for these studies; this way I can learn more about the format, and also take full advantage of its fantastic
support on Emacs.

* When?

Answers will appear here whenever I find free time and whenever I'm not stuck at something.
Someone said that some answers might demand a little bit more of advanced math so, if such a thing appears before me, I may end up trying to study the underlying
math before trying to answer the exercise as well.
I won't lie, I'll try to get some tips here and there from a few online communities which I think will be of great help, however I'm not going to copy anything
from anyone, as it will simply not help me grow in terms of knowledge -- and you should follow the same principle.

* Software

Some very reliable software was used to write these problems in a proper way, which I am going to
disclose here:

- Emacs editor;
- Org, an open document format for taking notes and schedule tasks;
- Graphviz, a tool for building graphs;
- =org-mode=, =graphviz-dot-mode= and =org-babel=, Emacs buffer modes for treating Org files, Graphviz Dot files and handling source code embedded in Org files on Emacs, respectively;
- LaTeX and htmlize for exporting Org into PDF and HTML files.

All source files for this notebook are stored in this repository, including graph images generated
for some of the exercises.

* Copyright

The text in this notebook has no license per se, since it is not software. Therefore, it can be considered public knowledge,
which you can use at your own risk.

The original code that I've written and that is included on the notebooks, however, has a license, unless it is copied
from the book. These are distributed under the MIT License, which means you can do whatever you want with it, but I cannot
be held responsible for any damage it may cause someday, as stated in the license itself -- not that it will or can cause
any damage, of course.

#+INCLUDE: "LICENSE" :only-contents t src text
